### PR TITLE
Partial codespaces support

### PR DESCRIPTION
**Pull request by kendrahavens**
Hi @jwidmer,

I just wanted to follow-up from our codespaces chat. Thank you for the pointer to this repo! The files in this PR will enable Azure Cosmos db emulator to install in a GitHub Codespace. No need to merge this PR, I just wanted to share info so I started a draft.

image
- Obviously it's not loading any posts, I'd have to take another look at the documentation on this sample to figure out if that's expected at this stage. :)

On the chance you are still interested in using a codespace:
- Complete installation by running `devinit init` in the Terminal.
- Start the Azure Cosmos DB emulator from the terminal with the below command in the Program Files\Azure Cosmos DB Emulator directory:
   `PS C:\Program Files\Azure Cosmos DB Emulator> .\Microsoft.Azure.Cosmos.Emulator.exe start`
- Set multiple start up projects by right-clicking on the solution > Properties
image

Thank you again for taking the time to chat with us!

### CODE REVIEW

**Comment by jwidmer** [comment]
Hi @kendrahavens!  Thank you very much!  This is great.  I am going to try to get this all working during my Twitch stream tomorrow (Wednesday 12PM Eastern Time).

**Comment by jwidmer** [comment]
> Obviously it's not loading any posts, I'd have to take another look at the documentation on this sample to figure out if that's expected at this stage. :)
Yes, there is no posts in a new installation (but maybe I should change that and insert a Hello World post on first launch).

**Comment by kendrahavens** [comment]
Awesome! Wish I could watch the stream, but I will be occupied. Let me know if you run into any issues. :)

**Comment by jwidmer** [comment]
@kendrahavens I finally got the codespaces support working and it is really nice!  Thank you!  

Where can I submit GitHub Codespaces feedback?  The two issues I ran into:

1. I need to run devinit init twice (the first time chocolatey fails) somewhere with 
`SqlServerLocalDb v11.0.2318.0 [Approved] - Possibly broken
sqlserverlocaldb package files install completed. Performing other installation steps.
Attempt to get headers for http://care.dlservice.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SqlLocalDB.MSI?lcid=1033&cprod=SQLDENEXPPOST32 failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://care.dlservice.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SqlLocalDB.MSI?lcid=1033&cprod=SQLDENEXPPOST32'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
Downloading SqlServerLocalDb 64 bit
  from 'http://care.dlservice.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SqlLocalDB.MSI?lcid=1033&cprod=SQLDENEXPPOST32'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://care.dlservice.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SqlLocalDB.MSI?lcid=1033&cprod=SQLDENEXPPOST32'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
The install of sqlserverlocaldb was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\SqlServerLocalDb\tools\chocolateyInstall.ps1'.`

2. The mssql install is long. It would be nice to be able to start with a container with sql server already installed.

**Pull request merged**
